cc_library(
    name = "ajson",
    srcs = [
        "ajson.cpp",
        "json_parser_visitor.cpp",
    ],
    hdrs = [
        "ajson.h",
        "json_parser_visitor.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//antlr:json",
    ],
)
